### ISSUE TITLE
Paste Relative Path Commands only works on markdown files

### ISSUE THREAD

**Issue by tekdj7** [brokensandals/paste-relative-path#2] opened 2021-01-04 07:07 UTC
Both commands work for markdown files.  However, for non-markdown files, it doesn't work. It be great if these 2 commands worked despite the file type, as there are cases where relative path is necessary and its not just for markdown.

Copied an absolute path.  Went to `Command Palette` on Visual Studio Code Mac, and ran the `Paste Relative Path` command, and it just pastes `.`. Running `Paste Relative Path as Markdown` command, creates a markdown type link, but still only puts `.` for the link.

**Comment by brokensandals** [comment] 2021-01-06 03:18
@tekdj7 The commands should work on any file type, and for me they do. You'll see a `.` if you try to paste a link from a file to itself. I.e., if you put `/foo/bar/file1.txt` on the clipboard, and you have /foo/bar/file1.txt open, it'll paste `.`; but if you had `/foo/bar/file2.txt` open it should paste `file1.txt`.

There's a [special case](https://github.com/brokensandals/paste-relative-path/blob/9b6ddb2ea3b21dc2c03766b129bbb22733097151/src/extension.ts#L12) in the code specifically for what to do when the path is the same; if you have a use case for different behavior, I'd be open to making it configurable.

**Comment by tekdj7** [comment] 2021-01-06 03:25
I recall testing with a different files. I will repeat my tests and let you know.

**Comment by brokensandals** [comment] 2021-01-10 18:40
Closing because I can't reproduce this issue, but it can be reopened if you encounter the problem again - let me know the source and destination paths that trigger the issue in case there's something weird going on for particular path strings.

**Closed by brokensandals** 2021-01-10 18:40 UTC

**Comment by tekdj7** [comment] 2021-01-10 20:12
Good to keep closed. Tested again and it's working. I'm guessing user error. Thanks.
